src/Entity/BaseEventi.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * App\Entity\Eventi
 *
 * @ORM\Entity()
 * @ORM\Table(name="Eventi")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base":"BaseEventi", "extended":"Eventi"})
 */
class BaseEventi
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $codice_evento;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $data_evento;

    /**
     * @ORM\Column(type="string", length=350, nullable=true)
     */
    protected $evento;

    /**
     * @ORM\Column(type="string", length=350, nullable=true)
     */
    protected $descrizione_evento;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $configurazioni;

    /**
     * @ORM\Column(name="`off`", type="boolean", nullable=true)
     */
    protected $off;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $stato_wf;

    /**
     * @ORM\OneToMany(targetEntity="Actionlogs", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="eventi_id_evento", nullable=false)
     */
    protected $actionlogs;

    /**
     * @ORM\OneToMany(targetEntity="Circoscrizioni", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="evento_id", nullable=false)
     */
    protected $circoscrizionis;

    /**
     * @ORM\OneToMany(targetEntity="Confxvotanti", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="evento_id", nullable=false)
     */
    protected $confxvotantis;

    /**
     * @ORM\OneToMany(targetEntity="Entexevento", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="evento_id", nullable=false)
     */
    protected $entexeventos;

    public function __construct()
    {
        $this->actionlogs = new ArrayCollection();
        $this->circoscrizionis = new ArrayCollection();
        $this->confxvotantis = new ArrayCollection();
        $this->entexeventos = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \App\Entity\Eventi
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of codice_evento.
     *
     * @param string $codice_evento
     * @return \App\Entity\Eventi
     */
    public function setCodiceEvento($codice_evento)
    {
        $this->codice_evento = $codice_evento;

        return $this;
    }

    /**
     * Get the value of codice_evento.
     *
     * @return string
     */
    public function getCodiceEvento()
    {
        return $this->codice_evento;
    }

    /**
     * Set the value of data_evento.
     *
     * @param \DateTime $data_evento
     * @return \App\Entity\Eventi
     */
    public function setDataEvento($data_evento)
    {
        $this->data_evento = $data_evento;

        return $this;
    }

    /**
     * Get the value of data_evento.
     *
     * @return \DateTime
     */
    public function getDataEvento()
    {
        return $this->data_evento;
    }

    /**
     * Set the value of evento.
     *
     * @param string $evento
     * @return \App\Entity\Eventi
     */
    public function setEvento($evento)
    {
        $this->evento = $evento;

        return $this;
    }

    /**
     * Get the value of evento.
     *
     * @return string
     */
    public function getEvento()
    {
        return $this->evento;
    }

    /**
     * Set the value of descrizione_evento.
     *
     * @param string $descrizione_evento
     * @return \App\Entity\Eventi
     */
    public function setDescrizioneEvento($descrizione_evento)
    {
        $this->descrizione_evento = $descrizione_evento;

        return $this;
    }

    /**
     * Get the value of descrizione_evento.
     *
     * @return string
     */
    public function getDescrizioneEvento()
    {
        return $this->descrizione_evento;
    }

    /**
     * Set the value of configurazioni.
     *
     * @param string $configurazioni
     * @return \App\Entity\Eventi
     */
    public function setConfigurazioni($configurazioni)
    {
        $this->configurazioni = $configurazioni;

        return $this;
    }

    /**
     * Get the value of configurazioni.
     *
     * @return string
     */
    public function getConfigurazioni()
    {
        return $this->configurazioni;
    }

    /**
     * Set the value of off.
     *
     * @param boolean $off
     * @return \App\Entity\Eventi
     */
    public function setOff($off)
    {
        $this->off = $off;

        return $this;
    }

    /**
     * Get the value of off.
     *
     * @return boolean
     */
    public function getOff()
    {
        return $this->off;
    }

    /**
     * Set the value of stato_wf.
     *
     * @param string $stato_wf
     * @return \App\Entity\Eventi
     */
    public function setStatoWf($stato_wf)
    {
        $this->stato_wf = $stato_wf;

        return $this;
    }

    /**
     * Get the value of stato_wf.
     *
     * @return string
     */
    public function getStatoWf()
    {
        return $this->stato_wf;
    }

    /**
     * Add Actionlogs entity to collection (one to many).
     *
     * @param \App\Entity\Actionlogs $actionlogs
     * @return \App\Entity\Eventi
     */
    public function addActionlogs(Actionlogs $actionlogs)
    {
        $this->actionlogs[] = $actionlogs;

        return $this;
    }

    /**
     * Remove Actionlogs entity from collection (one to many).
     *
     * @param \App\Entity\Actionlogs $actionlogs
     * @return \App\Entity\Eventi
     */
    public function removeActionlogs(Actionlogs $actionlogs)
    {
        $this->actionlogs->removeElement($actionlogs);

        return $this;
    }

    /**
     * Get Actionlogs entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getActionlogs()
    {
        return $this->actionlogs;
    }

    /**
     * Add Circoscrizioni entity to collection (one to many).
     *
     * @param \App\Entity\Circoscrizioni $circoscrizioni
     * @return \App\Entity\Eventi
     */
    public function addCircoscrizioni(Circoscrizioni $circoscrizioni)
    {
        $this->circoscrizionis[] = $circoscrizioni;

        return $this;
    }

    /**
     * Remove Circoscrizioni entity from collection (one to many).
     *
     * @param \App\Entity\Circoscrizioni $circoscrizioni
     * @return \App\Entity\Eventi
     */
    public function removeCircoscrizioni(Circoscrizioni $circoscrizioni)
    {
        $this->circoscrizionis->removeElement($circoscrizioni);

        return $this;
    }

    /**
     * Get Circoscrizioni entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCircoscrizionis()
    {
        return $this->circoscrizionis;
    }

    /**
     * Add Confxvotanti entity to collection (one to many).
     *
     * @param \App\Entity\Confxvotanti $confxvotanti
     * @return \App\Entity\Eventi
     */
    public function addConfxvotanti(Confxvotanti $confxvotanti)
    {
        $this->confxvotantis[] = $confxvotanti;

        return $this;
    }

    /**
     * Remove Confxvotanti entity from collection (one to many).
     *
     * @param \App\Entity\Confxvotanti $confxvotanti
     * @return \App\Entity\Eventi
     */
    public function removeConfxvotanti(Confxvotanti $confxvotanti)
    {
        $this->confxvotantis->removeElement($confxvotanti);

        return $this;
    }

    /**
     * Get Confxvotanti entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getConfxvotantis()
    {
        return $this->confxvotantis;
    }

    /**
     * Add Entexevento entity to collection (one to many).
     *
     * @param \App\Entity\Entexevento $entexevento
     * @return \App\Entity\Eventi
     */
    public function addEntexevento(Entexevento $entexevento)
    {
        $this->entexeventos[] = $entexevento;

        return $this;
    }

    /**
     * Remove Entexevento entity from collection (one to many).
     *
     * @param \App\Entity\Entexevento $entexevento
     * @return \App\Entity\Eventi
     */
    public function removeEntexevento(Entexevento $entexevento)
    {
        $this->entexeventos->removeElement($entexevento);

        return $this;
    }

    /**
     * Get Entexevento entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEntexeventos()
    {
        return $this->entexeventos;
    }

    public function __sleep()
    {
        return array('id', 'codice_evento', 'data_evento', 'evento', 'descrizione_evento', 'configurazioni', 'off', 'stato_wf');
    }
}

src/Entity/BaseRxliste.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * App\Entity\Rxliste
 *
 * @ORM\Entity()
 * @ORM\Table(name="Rxliste", indexes={@ORM\Index(name="fk_Rxliste_Enti1_idx", columns={"ente_id"}), @ORM\Index(name="index_id_source", columns={"id_source"})})
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base":"BaseRxliste", "extended":"Rxliste"})
 */
class BaseRxliste
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $ente_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $lista_desc;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $nome_cand;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $id_source;

    /**
     * @ORM\Column(name="`off`", type="boolean", nullable=true)
     */
    protected $off;

    /**
     * @ORM\Column(name="`timestamp`", type="datetime", nullable=true)
     */
    protected $timestamp;

    /**
     * @ORM\ManyToOne(targetEntity="Enti", inversedBy="rxlistes")
     * @ORM\JoinColumn(name="ente_id", referencedColumnName="id", nullable=false)
     */
    protected $enti;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \App\Entity\Rxliste
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of ente_id.
     *
     * @param integer $ente_id
     * @return \App\Entity\Rxliste
     */
    public function setEnteId($ente_id)
    {
        $this->ente_id = $ente_id;

        return $this;
    }

    /**
     * Get the value of ente_id.
     *
     * @return integer
     */
    public function getEnteId()
    {
        return $this->ente_id;
    }

    /**
     * Set the value of lista_desc.
     *
     * @param string $lista_desc
     * @return \App\Entity\Rxliste
     */
    public function setListaDesc($lista_desc)
    {
        $this->lista_desc = $lista_desc;

        return $this;
    }

    /**
     * Get the value of lista_desc.
     *
     * @return string
     */
    public function getListaDesc()
    {
        return $this->lista_desc;
    }

    /**
     * Set the value of nome_cand.
     *
     * @param string $nome_cand
     * @return \App\Entity\Rxliste
     */
    public function setNomeCand($nome_cand)
    {
        $this->nome_cand = $nome_cand;

        return $this;
    }

    /**
     * Get the value of nome_cand.
     *
     * @return string
     */
    public function getNomeCand()
    {
        return $this->nome_cand;
    }

    /**
     * Set the value of id_source.
     *
     * @param integer $id_source
     * @return \App\Entity\Rxliste
     */
    public function setIdSource($id_source)
    {
        $this->id_source = $id_source;

        return $this;
    }

    /**
     * Get the value of id_source.
     *
     * @return integer
     */
    public function getIdSource()
    {
        return $this->id_source;
    }

    /**
     * Set the value of off.
     *
     * @param boolean $off
     * @return \App\Entity\Rxliste
     */
    public function setOff($off)
    {
        $this->off = $off;

        return $this;
    }

    /**
     * Get the value of off.
     *
     * @return boolean
     */
    public function getOff()
    {
        return $this->off;
    }

    /**
     * Set the value of timestamp.
     *
     * @param \DateTime $timestamp
     * @return \App\Entity\Rxliste
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    /**
     * Get the value of timestamp.
     *
     * @return \DateTime
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Set Enti entity (many to one).
     *
     * @param \App\Entity\Enti $enti
     * @return \App\Entity\Rxliste
     */
    public function setEnti(Enti $enti = null)
    {
        $this->enti = $enti;

        return $this;
    }

    /**
     * Get Enti entity (many to one).
     *
     * @return \App\Entity\Enti
     */
    public function getEnti()
    {
        return $this->enti;
    }

    public function __sleep()
    {
        return array('id', 'ente_id', 'lista_desc', 'nome_cand', 'id_source', 'off', 'timestamp');
    }
}

templates/Csvdownload/candidatisecondari.down.html.twig
{% extends "Default/index.html.twig" %}
{% block javascripts %}
    {{ encore_entry_script_tags('configsave') }}

{% endblock %}
{% block subcontent %}
<use xlink:href="https://italia.github.io/bootstrap-italia/dist/svg/sprite.svg"></use>
<div class="section">

<div class="col-lg-12 mx-auto">

<div id="collapseDiv2" class="collapse-div" role="tablist">

{% for object  in visible_objects %}

  <div class="collapse-header" id="heading1a">
    <button data-toggle="collapse" data-target="#collapse{{ object.evento.id }}" aria-expanded="true" aria-controls="collapse1a">
      Evento: {{object.evento.evento}} del {{ object.evento.dataEvento| date('Y-m-d') }} (codice: {{ object.evento.codiceEvento }})
    </button>
  </div>
  <div id="collapse{{ object.evento.id }}" class="collapse show" role="tabpanel" aria-labelledby="heading1b">
      <div class="collapse-body">
 

{% for item in object.circoscrizioni %}
{% set circoscrizione = item.circoscrizione %}
Circoscrizione: {{ circoscrizione.circDesc}} (id: {{ circoscrizione.idTarget }})
 <table class="table table-sm table-responsive-sm table-striped bitable table-hover">
    <thead>
    <tr> 

        <th scope="col">Ordine Lista</th>
        <th scope="col">Nome lista</th>
        <th scope="col">Nome Candidato</th>
        <th scope="col">Cognome Candidato</th>
        <th scope="col">Ordine Candidato</th>
        <th scope="col">Zona</th>
        <th scope="col">Tipo lista</th>
    </tr>
    </thead>
    <tbody>
          {% for key,candidatoListe in item.candidati %}
          {% set candidato = candidatoListe.candidato %}
            
           
           
            {% for keylp,listaPreferenza in candidatoListe.liste %}
            {% set numCandidatiSecondari=0 %}
            {% set numCandidatiSecondariConfig=0 %}
            {% set lista = listaPreferenza.lista %}
                  {% for keylpc,candidatoSecondario in listaPreferenza.candidatisecondari %}
                   <tr>
                    <th scope="row">{{keylp}}</th>
                    <td>{{lista.listaDesc}}</td>
                    <td>{{candidatoSecondario.nome|upper}}</td>
                    <td>{{candidatoSecondario.cognome|upper}}</td>
                    <td>{{keylpc}}</td>
                    <td>1</td>
                    <td>LCC</td>
                    </tr>           
                  {% endfor %}
            {% endfor %}
          {% endfor %}
          
        </div>
{% endfor %}
     </tbody>
     </table>
     </div>
  </div>

{% endfor %}


  </div>







   <button type="button" class="btn btn-primary csvbutton" data-filename="candidati_secondari_LCC.csv">Export Csv</button>

<a href="{{ path('downCSVxSource') }}">
 <button type="button" class="btn btn-primary">{{  'buttons.go-back'|trans({}, 'App') }}</button>
 </a>
</div>

</div>

{% endblock %}

templates/Csvdownload/candidatoprincipale.down.html.twig
{% extends "Default/index.html.twig" %}

{% block javascripts %}
    {{ encore_entry_script_tags('configsave') }}

{% endblock %}


{% block subcontent %}
    <use xlink:href="https://italia.github.io/bootstrap-italia/dist/svg/sprite.svg"></use>
    <div class="section">

        <div class="col-lg-12 mx-auto">

            <div id="collapseDiv2" class="collapse-div" role="tablist">

                {% for object  in visible_objects %}

                    <div class="collapse-header" id="heading1a">
                        <button data-toggle="collapse" data-target="#collapse{{ object.evento.id }}" aria-expanded="true" aria-controls="collapse1a">
                            Evento: {{object.evento.evento}} del {{ object.evento.dataEvento| date('Y-m-d') }} (codice: {{ object.evento.codiceEvento }})
                        </button>
                    </div>
                    <div id="collapse{{ object.evento.id }}" class="collapse show" role="tabpanel" aria-labelledby="heading1b">
                        <div class="collapse-body">


                            {% for item in object.circoscrizioni %}
                                {% set circoscrizione = item.circoscrizione %}
                                Circoscrizione: {{ circoscrizione.circDesc}} (id: {{ circoscrizione.idTarget }})

                                <table class="table table-sm table-responsive-sm table-striped bitable table-hover">
                                    <thead>
                                        <tr> 

                                            <th scope="col">Ordine Candidato</th>
                                            <th scope="col">Nome lista</th>
                                            <th scope="col">Nome Candidato</th>
                                            <th scope="col">Cognome Candidato</th>
                                            <th scope="col">Ordine Lista</th>
                                            <th scope="col">Zona</th>
                                            <th scope="col">Tipo lista</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        {% for key,candidatoListe in item.candidati %}
                                            {% set candidato = candidatoListe.candidato %}

                                            {% for keylp,listaPreferenza in candidatoListe.liste %}
                                                {% set lista = listaPreferenza.lista %}

                                                <tr>
                                                    <th scope="row">{{key}}</th>
                                                    <td>{{lista.listaDesc}}</td>
                                                    <td>{{candidato.nome|upper}}</td>
                                                    <td>{{candidato.cognome|upper}}</td>
                                                    <td>{{keylp}}</td>
                                                    <td>1</td>
                                                    <td>LSS</td>
                                                </tr>           

                                            {% endfor %}


                                        {% endfor %}
                                    </tbody>
                                </table>






                            {% endfor %}

                        </div>
                    </div>

                {% endfor %}
                <button type="button" class="btn btn-primary csvbutton" data-filename="candidati_principali_LSS.csv">Export Csv</button>
                
                <a href="{{ path('downCSVxSource') }}">
                    <button type="button" class="btn btn-primary">{{  'buttons.go-back'|trans({}, 'App') }}</button>
                </a>

            </div>
        </div>

    </div>

{% endblock %}

templates/Csvdownload/csvdownload.home.html.twig
{% extends "Default/index.html.twig" %}

{% block subcontent %}


<div class="col-lg-10 mx-auto">

<div class="row">
  <div class="col-12 col-lg-12">
    <!--start card-->
    <div class="card-wrapper card-space">
      <div class="card card-bg">
        <div class="card-body">
          <h5 class="card-title">{{  'download.csv.main-cand'|trans({}, 'App') }}</h5>
          <p class="card-text"></p>
        <div class="it-card-footer">

          <a href="{{'/service/downCSVCandPrincxSource/'~  evento}}">
            <button type="button" class="btn btn-primary">{{  'buttons.action-exec'|trans({}, 'App') }}</button>
          </a>
        
        </div>
        </div>
      </div>
    </div>
    <!--end card-->
  </div>
</div>

<div class="row">
  <div class="col-12 col-lg-12">
    <!--start card-->
    <div class="card-wrapper card-space">
      <div class="card card-bg">
        <div class="card-body">
          <h5 class="card-title">{{  'download.csv.list'|trans({}, 'App') }}</h5>
          <p class="card-text"></p>
          <div class="it-card-footer">
           <a href="{{'/service/downCSVCandSecxSource/'~  evento}}">
    
            <button type="button" class="btn btn-primary">{{  'buttons.action-exec'|trans({}, 'App') }}</button>
          </a>
         
          </div>
        </div>
      </div>
    </div>
    <!--end card-->
  </div>
</div>
<a href="{{ path('welcome') }}">
 <button type="button" class="btn btn-primary">{{  'buttons.go-back'|trans({}, 'App') }}</button>
 </a>
</div>


{% endblock %}

templates/Csvdownload/sceltaEvento.html.twig
{% extends "@BiCore/layout.html.twig" %}
  

{% block content %}
{% block subcontent %}
    <!--h1>DIVO! {{  'home.benvenuto'|trans({}, 'App') }} {{app.user.username}}</h1-->

<div class="col-lg-10 mx-auto">
<use xlink:href="https://italia.github.io/bootstrap-italia/dist/svg/sprite.svg"></use>
{% if num_eventi > 0 %}
<div class="row">
  <div class="col-12 col-lg-12">
  <p>
  <h5> {{  'download.event.select'|trans({}, 'App') }}</h5> 
  </p>
  </div>
</div>
<!-- for -->
{% for evento in eventi %}
<div class="row">
  <div class="col-12 col-lg-12">
    <!--start card-->
    <div class="card-wrapper card-space">
      <div class="card card-bg">
        <div class="card-body">
            <div class="top-icon">
            <svg class="icon">

            </svg>
            </div>
            <h5 class="card-title">{{evento.eventi.evento}}</h5>
            <h5 class="card-title">ID:{{evento.eventi.id}} - CODICE: {{evento.eventi.codiceEvento}} - DATA: {{evento.eventi.dataEvento| date("d/m/Y") }} </h5>
          
          <p class="card-text"></p>
    
          <a class="read-more showSpinner" href="{{'downCSVxSource/'~  evento.eventi.id}}">
            <span class="text">{{  'buttons.data-download'|trans({}, 'App') }}</span>
            <svg class="icon">
              <use xlink:href="#it-arrow-right"></use>
            </svg>
          </a>
        </div>
      </div>
    </div>
    <!--end card-->
  </div>

  </div>
 
{% endfor %}
{% else %}
<div class="row">
  <div class="col-12 col-lg-12">
  <p>
  <h5>{{  'download.event.alert'|trans({}, 'App') }}</h5> 
  </p>
  </div>
</div>
{% endif %}
</div>

</div>



</div>
{% endblock %}




{% endblock %}