src/Entity/BaseEventi.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * App\Entity\Eventi
 *
 * @ORM\Entity()
 * @ORM\Table(name="Eventi")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base":"BaseEventi", "extended":"Eventi"})
 */
class BaseEventi
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $codice_evento;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $data_evento;

    /**
     * @ORM\Column(type="string", length=350, nullable=true)
     */
    protected $evento;

    /**
     * @ORM\Column(type="string", length=350, nullable=true)
     */
    protected $descrizione_evento;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $configurazioni;

    /**
     * @ORM\Column(name="`off`", type="boolean", nullable=true)
     */
    protected $off;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $stato_wf;

    /**
     * @ORM\OneToMany(targetEntity="Actionlogs", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="eventi_id_evento", nullable=false)
     */
    protected $actionlogs;

    /**
     * @ORM\OneToMany(targetEntity="Circoscrizioni", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="evento_id", nullable=false)
     */
    protected $circoscrizionis;

    /**
     * @ORM\OneToMany(targetEntity="Confxvotanti", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="evento_id", nullable=false)
     */
    protected $confxvotantis;

    /**
     * @ORM\OneToMany(targetEntity="Entexevento", mappedBy="eventi")
     * @ORM\JoinColumn(name="id", referencedColumnName="evento_id", nullable=false)
     */
    protected $entexeventos;

    public function __construct()
    {
        $this->actionlogs = new ArrayCollection();
        $this->circoscrizionis = new ArrayCollection();
        $this->confxvotantis = new ArrayCollection();
        $this->entexeventos = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \App\Entity\Eventi
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of codice_evento.
     *
     * @param string $codice_evento
     * @return \App\Entity\Eventi
     */
    public function setCodiceEvento($codice_evento)
    {
        $this->codice_evento = $codice_evento;

        return $this;
    }

    /**
     * Get the value of codice_evento.
     *
     * @return string
     */
    public function getCodiceEvento()
    {
        return $this->codice_evento;
    }

    /**
     * Set the value of data_evento.
     *
     * @param \DateTime $data_evento
     * @return \App\Entity\Eventi
     */
    public function setDataEvento($data_evento)
    {
        $this->data_evento = $data_evento;

        return $this;
    }

    /**
     * Get the value of data_evento.
     *
     * @return \DateTime
     */
    public function getDataEvento()
    {
        return $this->data_evento;
    }

    /**
     * Set the value of evento.
     *
     * @param string $evento
     * @return \App\Entity\Eventi
     */
    public function setEvento($evento)
    {
        $this->evento = $evento;

        return $this;
    }

    /**
     * Get the value of evento.
     *
     * @return string
     */
    public function getEvento()
    {
        return $this->evento;
    }

    /**
     * Set the value of descrizione_evento.
     *
     * @param string $descrizione_evento
     * @return \App\Entity\Eventi
     */
    public function setDescrizioneEvento($descrizione_evento)
    {
        $this->descrizione_evento = $descrizione_evento;

        return $this;
    }

    /**
     * Get the value of descrizione_evento.
     *
     * @return string
     */
    public function getDescrizioneEvento()
    {
        return $this->descrizione_evento;
    }

    /**
     * Set the value of configurazioni.
     *
     * @param string $configurazioni
     * @return \App\Entity\Eventi
     */
    public function setConfigurazioni($configurazioni)
    {
        $this->configurazioni = $configurazioni;

        return $this;
    }

    /**
     * Get the value of configurazioni.
     *
     * @return string
     */
    public function getConfigurazioni()
    {
        return $this->configurazioni;
    }

    /**
     * Set the value of off.
     *
     * @param boolean $off
     * @return \App\Entity\Eventi
     */
    public function setOff($off)
    {
        $this->off = $off;

        return $this;
    }

    /**
     * Get the value of off.
     *
     * @return boolean
     */
    public function getOff()
    {
        return $this->off;
    }

    /**
     * Set the value of stato_wf.
     *
     * @param string $stato_wf
     * @return \App\Entity\Eventi
     */
    public function setStatoWf($stato_wf)
    {
        $this->stato_wf = $stato_wf;

        return $this;
    }

    /**
     * Get the value of stato_wf.
     *
     * @return string
     */
    public function getStatoWf()
    {
        return $this->stato_wf;
    }

    /**
     * Add Actionlogs entity to collection (one to many).
     *
     * @param \App\Entity\Actionlogs $actionlogs
     * @return \App\Entity\Eventi
     */
    public function addActionlogs(Actionlogs $actionlogs)
    {
        $this->actionlogs[] = $actionlogs;

        return $this;
    }

    /**
     * Remove Actionlogs entity from collection (one to many).
     *
     * @param \App\Entity\Actionlogs $actionlogs
     * @return \App\Entity\Eventi
     */
    public function removeActionlogs(Actionlogs $actionlogs)
    {
        $this->actionlogs->removeElement($actionlogs);

        return $this;
    }

    /**
     * Get Actionlogs entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getActionlogs()
    {
        return $this->actionlogs;
    }

    /**
     * Add Circoscrizioni entity to collection (one to many).
     *
     * @param \App\Entity\Circoscrizioni $circoscrizioni
     * @return \App\Entity\Eventi
     */
    public function addCircoscrizioni(Circoscrizioni $circoscrizioni)
    {
        $this->circoscrizionis[] = $circoscrizioni;

        return $this;
    }

    /**
     * Remove Circoscrizioni entity from collection (one to many).
     *
     * @param \App\Entity\Circoscrizioni $circoscrizioni
     * @return \App\Entity\Eventi
     */
    public function removeCircoscrizioni(Circoscrizioni $circoscrizioni)
    {
        $this->circoscrizionis->removeElement($circoscrizioni);

        return $this;
    }

    /**
     * Get Circoscrizioni entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCircoscrizionis()
    {
        return $this->circoscrizionis;
    }

    /**
     * Add Confxvotanti entity to collection (one to many).
     *
     * @param \App\Entity\Confxvotanti $confxvotanti
     * @return \App\Entity\Eventi
     */
    public function addConfxvotanti(Confxvotanti $confxvotanti)
    {
        $this->confxvotantis[] = $confxvotanti;

        return $this;
    }

    /**
     * Remove Confxvotanti entity from collection (one to many).
     *
     * @param \App\Entity\Confxvotanti $confxvotanti
     * @return \App\Entity\Eventi
     */
    public function removeConfxvotanti(Confxvotanti $confxvotanti)
    {
        $this->confxvotantis->removeElement($confxvotanti);

        return $this;
    }

    /**
     * Get Confxvotanti entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getConfxvotantis()
    {
        return $this->confxvotantis;
    }

    /**
     * Add Entexevento entity to collection (one to many).
     *
     * @param \App\Entity\Entexevento $entexevento
     * @return \App\Entity\Eventi
     */
    public function addEntexevento(Entexevento $entexevento)
    {
        $this->entexeventos[] = $entexevento;

        return $this;
    }

    /**
     * Remove Entexevento entity from collection (one to many).
     *
     * @param \App\Entity\Entexevento $entexevento
     * @return \App\Entity\Eventi
     */
    public function removeEntexevento(Entexevento $entexevento)
    {
        $this->entexeventos->removeElement($entexevento);

        return $this;
    }

    /**
     * Get Entexevento entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEntexeventos()
    {
        return $this->entexeventos;
    }

    public function __sleep()
    {
        return array('id', 'codice_evento', 'data_evento', 'evento', 'descrizione_evento', 'configurazioni', 'off', 'stato_wf');
    }
}

templates/source/source.down.html.twig
{% extends "Default/index.html.twig" %}

{% block subcontent %}


<div class="col-lg-10 mx-auto">

<div class="row">
  <div class="col-12 col-lg-12">
    <!--start card-->
    <div class="card-wrapper card-space">
      <div class="card card-bg">
        <div class="card-body">
          <h5 class="card-title">SERVICE 2.1 - RECUPERA COMUNICAZIONI ELETTORALI</h5>
          <p class="card-text">Restituisce l'elenco delle comunicazioni elettorali attivate sul sistema AWE per l'utente specificato e
relativo all'ente (comune) passato in input. Ogni comunicazione è legata ad un evento elettorale di cui
viene restituito il tipo.</p>
        <div class="it-card-footer">
          <a href="{{ path('downComunicazionieventi') }}">
            <button type="button" class="btn btn-primary">Esegui</button>
          </a>
          <a href="{{ path('readComunicazioniEventi') }}">
            <button type="button" class="btn btn-outline-primary">Ispeziona</button>
          </a>
        </div>
        </div>
      </div>
    </div>
    <!--end card-->
  </div>
</div>

<div class="row">
  <div class="col-12 col-lg-12">
    <!--start card-->
    <div class="card-wrapper card-space">
      <div class="card card-bg">
        <div class="card-body">
          <h5 class="card-title">SERVICE 2.2 - RECUPERA LISTE E CANDIDATI</h5>
          <p class="card-text">E’ presente il concetto di circoscrizione, in quanto le stesse liste possono essere presentate con diversi
candidati o con i candidati in diversa posizione, se un territorio è suddiviso in circoscrizioni. Per lo stesso
motivo, per tutte le comunicazioni riguardanti voti e preferenze, è stata prevista come input l'informazione
sulla circoscrizione, in modo da facilitare i controlli di coerenza prima dell'inserimento.</p>
          <div class="it-card-footer">
          <a href="{{ path('downCandidatiListe') }}">
            <button type="button" class="btn btn-primary">Esegui</button>
          </a>
           <a href="{{ path('readCandidatiListe') }}">
            <button type="button" class="btn btn-outline-primary">Ispeziona</button>
          </a>
          </div>
        </div>
      </div>
    </div>
    <!--end card-->
  </div>
</div>
<a href="{{ path('welcome') }}">
 <button type="button" class="btn btn-primary">{{  'buttons.go-back'|trans({}, 'App') }}</button>
 </a>
</div>


{% endblock %}

templates/source/source.preferenze.html.twig
{% extends "Default/index.html.twig" %}

{% block javascripts %}
 {{ encore_entry_script_tags('alert') }}
 {{ encore_entry_script_tags('divoSlicer') }}
  {{ encore_entry_script_tags('openCollapse') }}
{% endblock %}

{% block subcontent %}

<use xlink:href="https://italia.github.io/bootstrap-italia/dist/svg/sprite.svg"></use>

<div class="section">

{% if communication_esito is defined %}
    {% if communication_esito.esito.codice == 1 %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">{{ communication_esito.esito.descrizione }}</h4>
      <p>L'operazione di invio dati è stata effettuata con successo.</p>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    {% if communication_esito.esito.codice != 1 %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
    L'operazione di invio dati ha riscontrato un errore: "<b>{{ communication_esito.esito.descrizione }}</b>".
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <br>
    {% endif %}
{% endif %}

<div class="col-lg-10 mx-auto">

<h3>Preferenze: Ispezione ed Invio</h3>

<div id="collapseDiv2" class="collapse-div" role="tablist">

{% for key,item in data %}

<div class="collapse-header" id="heading1a">
    <button data-toggle="collapse" data-target="#collapse-{{item.event.id}}" aria-expanded="true" aria-controls="collapse1a">
      {{ item.event.evento }} - {{ item.event.descrizioneEvento }} 
      <span class="badge badge-pill badge-primary">{{ item.event.statoWfDesc }}</span> <br>
    </button>
</div>
<div id="collapse-{{item.event.id}}" class="collapse show" role="tabpanel" aria-labelledby="heading1b">
      <div class="collapse-body">

<p>
  <button type="button" class="btn btn-primary btn-icon multiSlicer" data-eventid={{ item.event.id }} data-topic="preferenze" data-topic-text="Sezioni aggiornate" data-path="/{{ item.event.id }}/preferenze/sezioni/changed" aria-disabled="true">
      <svg class="icon icon-white"><use xlink:href="#it-arrow-up-circle"></use></svg>
      <span>Invia Preferenze</span>
  </button>

  <button class="btn btn-secondary-outline btn-icon" type="button" data-toggle="collapse" data-target="#collapseMultipleRange" aria-expanded="false" aria-controls="collapseExample">
  <svg class="icon icon-primary"><use xlink:href="#it-zoom-in"></use></svg>
  <!--span></span-->
  </button>
</p>
<div class="collapse" id="collapseMultipleRange">
  <div class="callout">
    <div class="callout-title"><span class="sr-only">Confermato</span>Invio Selettivo</div>
    <p>Si selezioni la <b>Sezione Iniziale</b> e la <b>Sezione Finale</b> del proprio intervallo di interesse.
    La procedura invierà i dati delle Preferenze relativi all'intervallo indicato (incluse la sezione iniziale e finale).<br>
    L'operazione di invio potrebbe richiedere alcuni minuti nel caso si siano selezionate molte sezioni.</p>
    
    <div class="form-row">
        <div class="form-group col-md-6">
          <div class="bootstrap-select-wrapper">
            <label>Sezione Iniziale</label>
            <select title="Scegli una sezione" id="start-sec-{{ item.event.id }}">
            {% for struct in item.array %}
              <option value="{{ struct.sezione.sezione.id }}">{{ struct.sezione.sezione.descrizione }}</option>
            {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group col-md-6">
          <div class="bootstrap-select-wrapper">
            <label>Sezione Finale</label>
           <select title="Scegli una sezione" id="end-sec-{{ item.event.id }}">
            {% for struct in item.array %}
              <option value="{{ struct.sezione.sezione.id }}">{{ struct.sezione.sezione.descrizione }}</option>
            {% endfor %}
            </select>
          </div>
        </div>
    </div>
    
    <button type="button" class="btn btn-primary btn-icon btn-sm multiSlicer" data-eventid={{ item.event.id }} data-topic="preferenze" data-topic-text="Sezioni indicate" data-path="/{{ item.event.id }}/sezioni/range" aria-disabled="true">
        <svg class="icon icon-white"><use xlink:href="#it-upload"></use></svg>
        <span>Invia intervallo</span>
    </button>
  </div>

</div>

      <h5>Dettaglio per sezione</h5> 
      

      {% for struct in item.array %}
      {% set iter = 0 %}

<div class="collapse-header" id="heading1a">
    <button data-toggle="collapse" data-target="#collapse{{ struct.sezione.sezione.id }}" aria-expanded="true" aria-controls="collapse1a">
      {{ struct.sezione.evento.evento }} {{ struct.sezione.evento.descrizioneEvento}} - {{struct.sezione.sezione.descrizione}} 
      <span class="badge badge-pill badge-primary"> {{ struct.sezione.sezione.statoWfDesc }}</span>
    </button>
  </div>
  
  <div id="collapse{{ struct.sezione.sezione.id }}" class="collapse collapse-div-open" role="tabpanel" aria-labelledby="heading1b">
      <div class="collapse-body">
    
 
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Lista</th>
      <th scope="col">Candidato Secondario</th>
      <th scope="col">Voti Totali</th>
    </tr>
  </thead>
  <tbody>


  {% for preferenza in struct.preferenze|sort((a, b) => b.lista_desc <=> a.lista_desc) %}

  {% set iter =iter +1  %}
    <tr class="{% if preferenza.bitnew != 0 %} record_nuovo table-primary {% else %} table-secondary {% endif %}">
      <td><small>{{ preferenza.lista_desc }}</small>
      </td>
      <td><small><b>{{ preferenza.cognome }} {{ preferenza.nome }}</b>
      ({{ preferenza.sesso }}), {{ preferenza.luogo_nascita }} </small></td>
      <td><small><b>{{ preferenza.numero_voti }}</b></small></td>
    </tr>

  {% endfor %}

    <tr>
      <td>Totale voti liste preferenza
      </td>
      <td></td>
      <td><b>{{ struct.totaleVoti }}</b></td>
    </tr>


  </tbody>
</table>
{% if iter > 0 %}
  <a href="{{ path('pushPreferenze', { 'sectionid': struct.sezione.sezione.id }) }}">
 <button type="button" class="btn btn-outline-primary btn-sm">
 <span>Invia ({{ struct.sezione.sezione.descrizione }} - {{struct.sezione.evento.evento}})</span>
 </button>
 </a>
{% endif %}

     </div>
  </div>


{% endfor %}

      </div> {# closing id="collapse body #}
</div> {# closing id="collapse-item.event.id" #}

{% endfor %}

  </div>


<a href="{{ path('sendRTdata') }}">
 <button type="button" class="btn btn-primary">{{  'buttons.go-back'|trans({}, 'App') }}</button>
 </a>

</div>

</div>

{% endblock %}

templates/source/source.quick.affluenze.html.twig
{% extends "Default/index.html.twig" %}

{% block javascripts %}
 {{ encore_entry_script_tags('alert') }}
 {{ encore_entry_script_tags('divoSlicer') }}
 {{ encore_entry_script_tags('openCollapse') }}
{% endblock %}

{% block subcontent %}

<use xlink:href="https://italia.github.io/bootstrap-italia/dist/svg/sprite.svg"></use>

<div class="section">

{% if communication_esito is defined %}
    {% if communication_esito.esito.codice == 1 %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">{{ communication_esito.esito.descrizione }}</h4>
      <p>L'operazione di invio dati è stata effettuata con successo.</p>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    {% if communication_esito.esito.codice != 1 %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
    L'operazione di invio dati ha riscontrato un errore: "<b>{{ communication_esito.esito.descrizione }}</b>".
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
{% endif %}

<div class="col-lg-10 mx-auto">

<h3>Affluenze: Ispezione ed Invio</h3>

<div id="collapseDiv2" class="collapse-div" role="tablist">

{% for item  in data|sort((a, b) => a.comunicazione.id <=> b.comunicazione.id) %}
  <div class="collapse-header" id="heading1a">
    <button data-toggle="collapse" data-target="#collapse{{ item.comunicazione.id }}" aria-expanded="true" aria-controls="collapse1a">
      <small>Evento (ID: {{  item.eventoid }}): {{ item.evento }} {{ item.eventodesc}}</small> <span class="badge badge-pill badge-primary">{{ item.eventostatus }}</span> 
      <br><small>Comunicazione:</small> {{item.comunicazione.comunicazioneDesc}} 
    </button>
  </div>
  <div id="collapse{{ item.comunicazione.id }}" class="collapse collapse-div-open" role="tabpanel" aria-labelledby="heading1b">
      <div class="collapse-body">



<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col"># Sez.</th>
      <th scope="col">Sez.</th>
      <th scope="col">Voti Maschi</th>
      <th scope="col">Voti Femmine</th>
      <th scope="col">Voti Totali</th>
    </tr>
  </thead>
  <tbody>
  {% set sum = 0 %}

{% for affluenza in item.affluenze %}    
     <tr class="text-sm {% if affluenza.bitnew != 0 %} record_nuovo table-primary {% endif %} ">
      <th scope="row">{{affluenza.numero}}</th>
      <td>{{ affluenza.descrizione }} <span class="badge badge-pill badge-primary">{{ affluenza.statowfdesc }}</span></td>
      <td>
      {% if affluenza.num_votanti_maschi is defined %} 
        {{ affluenza.num_votanti_maschi }}
      {% else %}
        -
      {% endif %}
      </td>
      <td>
      {% if affluenza.num_votanti_femmine is defined %} 
        {{ affluenza.num_votanti_femmine }}
      {% else %}
        -
      {% endif %}
      </td>
      <td>
      {% if item.includeAffluenzaMF == 1 %}
        {{ affluenza.num_votanti_femmine + affluenza.num_votanti_maschi }}
        {% set sum = sum + affluenza.num_votanti_femmine + affluenza.num_votanti_maschi %} 
      {% else %}
          {{ affluenza.num_votanti_totali }}
        {% set sum = sum + affluenza.num_votanti_totali %} 
      {% endif %}
      </td>
    </tr>

{% endfor %}
    <tr class="text-sm">
      <th scope="row">Totale</th>
      <td>Totale voti</td>
      <td></td><td></td><td>{{ sum }}</td>
    </tr>
  </tbody>
</table>

     </div>

    
    <button type="button" class="btn btn-primary btn-sm divo-post-data" data-eventid={{ item.eventoid }} data-topic=votantiChanged data-itemid={{ item.comunicazione.id }}>
      <svg class="icon icon-white"><use xlink:href="#it-arrow-up-circle"></use></svg>
      <span>Invia dati SOLO MODIFICATI({{item.comunicazione.comunicazioneDesc}})</span>
    </button> 
    <button type="button" class="btn btn-primary btn-sm divo-post-data" data-eventid={{ item.eventoid }} data-topic=votanti data-itemid={{ item.comunicazione.id }}>
      <svg class="icon icon-white"><use xlink:href="#it-arrow-up-circle"></use></svg>
      <span>Invia dati ({{item.comunicazione.comunicazioneDesc}})</span>
    </button> 
    
  </div>
   <p></p>

{% endfor %}

  </div>

<br>
<a href="{{ path('sendRTdata') }}">
 <button type="button" class="btn btn-primary">{{  'buttons.go-back'|trans({}, 'App') }}</button>
 </a>

</div>

</div>

{% endblock %}